name: first
main: fi.mariapori.first.first
version: 1.1
commands:
   dimang:
      description: Antaa 20 timanttia
      usage: /dimang
      permission: first.dimang
   buyop:
      description: Osta operaattori 10 timantilla
      usage: /buyop
      permission: first.buyop