name: first
main: fi.mariapori.first.first
version: 1.0
commands:
   dimang:
      description: Antaa 20 timanttia
      usage: /dimang
      permission: first.dimang
   tele:
      description: Teleporttaa pelaajaan
      usage: /tele <pelaaja>
      permission: first.tele